New action for add or change password for the OV
Som-Energia/openerp-somrepresenta pull request #3
Opened 2023-11-27 08:42 UTC by MariteSomEnergia

## Description

A user wants to create or reset a password for a res_partner.

## Changes

- Action added to res_partner allowing teh creation or reset of a password.
- The password is registered in the OV server available.
- The password is also stored in Notes then the email can recover the password.
- An email is sent to the OV user containing the password generated

## Deploy notes
X-API-KEY should be set in erp config  file.

2023-11-29 08:19 UTC, destanyol requested changes

2023-11-29 08:19 UTC, destanyol commented on som_users/wizard/wizard_create_change_password.py
> +        import pudb; pu.db
Eliminar pudb

2023-11-29 08:22 UTC, destanyol commented on som_users/data/email_template_data.xml
> +            <field name="def_bcc">support.17062.b8d9f4469fa4d856@helpscout.net</field>
??

2023-12-04 10:28 UTC, MariteSomEnergia commented on som_users/data/email_template_data.xml
> +            <field name="def_bcc">support.17062.b8d9f4469fa4d856@helpscout.net</field>
fet

2023-12-04 15:02 UTC, merged